import 'dotenv/config';
import axios from 'axios';

/**
 * Fashion Analysis result interface
 * Rich metadata generated by AI vision analysis for fashion product images
 */
export interface FashionAnalysis {
    occasions: string[]; // 3-5 specific events/settings (e.g., "black_tie_gala", "summer_wedding_guest")
    vibes: string[]; // 3-5 aesthetic/mood keywords (e.g., "old_money_elegant", "y2k_playful")
    body_types: string[]; // Body shapes this design flatters (e.g., "hourglass_enhancing", "pear_shape_friendly")
    seasonal_suitability: string[]; // Best seasons/weather (e.g., "peak_summer", "mild_spring_autumn")
    styling_tips: string; // 1-2 sentence professional styling tip
}

/**
 * Configuration for Pinkyne API
 */
const PINKYNE_API_KEY = process.env.PINKYNE_API_KEY;
const PINKYNE_BASE_URL = process.env.PINKYNE_API_BASE_URL || 'https://api.pinkyne.com/v1';
const MODEL_NAME = 'gpt-4o-mini';

/**
 * Extracts JSON from LLM response (supports code blocks and plain JSON)
 */
function extractJson(content: string): any {
    // Try to extract from markdown code block first
    const jsonMatch =
        content.match(/```json\s*([\s\S]*?)\s*```/i) ||
        content.match(/```\s*([\s\S]*?)\s*```/i);

    let jsonString = jsonMatch ? jsonMatch[1] : content;

    // Trim whitespace
    jsonString = jsonString.trim();

    // Try to isolate the JSON object between first '{' and last '}'
    const firstBrace = jsonString.indexOf('{');
    const lastBrace = jsonString.lastIndexOf('}');
    if (firstBrace !== -1 && lastBrace !== -1 && lastBrace > firstBrace) {
        jsonString = jsonString.slice(firstBrace, lastBrace + 1);
    }

    // Parse JSON (will throw if invalid)
    return JSON.parse(jsonString);
}

/**
 * Validates that the parsed object has the expected FashionAnalysis structure
 */
function validateFashionAnalysis(obj: any): obj is FashionAnalysis {
    return (
        obj &&
        typeof obj === 'object' &&
        Array.isArray(obj.occasions) &&
        Array.isArray(obj.vibes) &&
        Array.isArray(obj.body_types) &&
        Array.isArray(obj.seasonal_suitability) &&
        typeof obj.styling_tips === 'string'
    );
}

/**
 * Analyzes a fashion product image using Pinkyne API Vision capabilities.
 * Generates rich, stylist-level metadata for the specific color/pattern variation.
 * 
 * @param imageUrl - Direct URL of the product image to analyze
 * @param productContext - Optional context string (e.g., "Silk Evening Clutch") to help the AI
 * @returns FashionAnalysis object with rich metadata, or null if analysis fails
 */
export async function analyzeFashionImage(
    imageUrl: string,
    productContext?: string
): Promise<FashionAnalysis | null> {
    if (!PINKYNE_API_KEY) {
        console.error('❌ PINKYNE_API_KEY environment variable is not set');
        return null;
    }

    if (!imageUrl || !imageUrl.trim()) {
        console.error('❌ Image URL is required');
        return null;
    }

    // Construct the "Fashionista" prompt
    const prompt = `ROLE: You are a very fastidiously world-renowned High-Fashion Stylist and Image Consultant. Your eyes see beyond fabric; they see occasions, personalities, and styling potential.

CONTEXT: The item is: "${productContext || 'A fashion item'}".

TASK: Analyze the specific clothing/accessory variation shown in the image URL. Provide a deep fashion analysis.

OUTPUT REQUIREMENTS (Strict JSON format):

Return a single JSON object with these keys:

- \`occasions\` (array of strings): List 3-5 specific events/settings this item is PERFECT for (e.g., "black_tie_gala", "summer_wedding_guest", "creative_office", "casual_brunch", "club_night"). Be specific.

- \`vibes\` (array of strings): List 3-5 keywords describing the aesthetic/mood (e.g., "old_money_elegant", "y2k_playful", "minimalist_chic", "bohemian_free", "edgy_rocker").

- \`body_types\` (array of strings): Which body shapes or features does this specific cut/design flatter the most? (e.g., "hourglass_enhancing", "pear_shape_friendly", "creates_curves", "elongates_legs", "universally_flattering").

- \`seasonal_suitability\` (array of strings): Best seasons or weather conditions (e.g., "peak_summer", "mild_spring_autumn", "winter_layering", "all_season").

- \`styling_tips\` (string): A professional, 1-2 sentence tip on how to style this item to maximize its potential (e.g., "Pair with a sleek slip dress and stiletto heels for a gala, or dress down with high-waisted trousers for a sophisticated dinner.").

Important: Be critical and specific to the image. A "Pink Floral Dress" has a totally different vibe from a "Black Bodycon Dress".

Return ONLY raw JSON, no markdown formatting, no explanation.`;

    // Construct the API payload
    const payload = {
        model: MODEL_NAME,
        messages: [
            {
                role: 'user',
                content: [
                    { type: 'text', text: prompt },
                    {
                        type: 'image_url',
                        image_url: {
                            url: imageUrl,
                        },
                    },
                ],
            },
        ],
        max_tokens: 500,
        temperature: 0.4, // Slightly creative but focused
    };

    try {
        // Make API call to Pinkyne
        const response = await axios.post(
            `${PINKYNE_BASE_URL.replace(/\/+$/, '')}/chat/completions`,
            payload,
            {
                headers: {
                    'Content-Type': 'application/json',
                    Authorization: `Bearer ${PINKYNE_API_KEY}`,
                },
                timeout: 30000, // 30 second timeout
            }
        );

        // Extract content from response
        const content: string | undefined =
            response.data?.choices?.[0]?.message?.content ?? response.data?.choices?.[0]?.message;

        if (!content) {
            console.error('❌ Empty response from Pinkyne API');
            return null;
        }

        // Parse JSON from response
        let parsed: any;
        try {
            parsed = extractJson(content);
        } catch (err) {
            console.error('❌ Failed to parse JSON from API response:', err);
            console.error('Raw content preview:', content.slice(0, 500));
            return null;
        }

        // Validate the structure
        if (!validateFashionAnalysis(parsed)) {
            console.error('❌ Invalid FashionAnalysis structure in API response');
            console.error('Received:', JSON.stringify(parsed, null, 2));
            return null;
        }

        // Ensure arrays are not empty (fill with defaults if needed)
        const analysis: FashionAnalysis = {
            occasions: parsed.occasions && parsed.occasions.length > 0 ? parsed.occasions : [],
            vibes: parsed.vibes && parsed.vibes.length > 0 ? parsed.vibes : [],
            body_types: parsed.body_types && parsed.body_types.length > 0 ? parsed.body_types : [],
            seasonal_suitability:
                parsed.seasonal_suitability && parsed.seasonal_suitability.length > 0
                    ? parsed.seasonal_suitability
                    : [],
            styling_tips: parsed.styling_tips || '',
        };

        return analysis;
    } catch (error) {
        if (axios.isAxiosError(error)) {
            if (error.response) {
                console.error(
                    `❌ Pinkyne API error: ${error.response.status} - ${JSON.stringify(error.response.data)}`
                );
            } else {
                console.error(`❌ Network error calling Pinkyne API: ${error.message}`);
            }
        } else {
            console.error(
                `❌ Error analyzing fashion image: ${error instanceof Error ? error.message : String(error)}`
            );
        }
        return null;
    }
}


